# -*- coding: utf-8 -*-
"""vroomies.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ApOVLOv5uhR4XswzReD3FHcR_0YSN6qY
"""

# import funcs

# get streamlit
!pip install streamlit
!pip install plotly

import streamlit as st
import numpy as np
import pandas as pd
import plotly.express as px

# get dataset

base_url = "https://raw.githubusercontent.com/SZRoberson/CQ2026_DataTrack/main/data/"
filenames = ["LapTimes.csv", "RaceResults.csv"]


lap_df = pd.read_csv(base_url + filenames[0])
race_df = pd.read_csv(base_url + filenames[1])

print("Successfully loaded the dataframes:")


print("Laptimes")
display(lap_df.head())

print("RaceResults")
display(lap_df.head())



"""## Identify Key Season Metrics


"""

df_race_results = df_dict['RaceResults']

print("Head of RaceResults DataFrame:")
display(df_race_results.head())

print("\nInformation about RaceResults DataFrame:")
df_race_results.info()

"""## Prepare Data for Visualization

"""

import pandas as pd

base_url = "https://raw.githubusercontent.com/SZRoberson/CQ2026_DataTrack/main/data/"
race_results_url = base_url + "RaceResults.csv"

# Reload RaceResults.csv to ensure it's not empty
df_dict['RaceResults'] = pd.read_csv(race_results_url)

print("Reloaded RaceResults DataFrame:")
display(df_dict['RaceResults'].head())
print(f"Shape of reloaded RaceResults: {df_dict['RaceResults'].shape}")

df_driver_wins = df_dict['RaceResults'][df_dict['RaceResults']['Position'] == 1].groupby('FullName').agg(Wins=('FullName', 'count')).reset_index()
df_constructor_points = df_dict['RaceResults'].groupby(['Event Name', 'TeamName'])['Points'].sum().reset_index(name='Points')

import pandas as pd
import plotly.express as px

# 1. Bar Chart for Total Race Wins per Driver
fig_wins = px.bar(df_driver_wins,
                  x='FullName',
                  y='Wins',
                  title='Total Race Wins per 1st Place Driver',
                  labels={'FullName': 'Driver', 'Wins': 'Total Wins'},
                  color='FullName', # Assign color to each driver for better visual distinction
                  text='Wins',
                  template='ggplot2') # Display wins on top of bars
fig_wins.update_layout(xaxis={'categoryorder':'total descending'})
fig_wins.show()

# 2. Line Chart for Total Championship Points per Constructor
fig_points = px.bar(df_constructor_points,
                     x='TeamName',
                     y='Points',
                     color='TeamName', # Differentiate lines by TeamName
                     title='Total Championship Points per Team',
                     labels={'Season': 'Season', 'Points': 'Total Points', 'TeamName': 'Team Name'},
                    template='ggplot2') # Add markers to the line for each point
fig_points.update_xaxes(tickmode='linear') # Ensure all seasons are shown as distinct ticks
fig_points.show()

"""Making the model??????"""

driver_stats = {}

# Convert 'LapTime' column to timedelta objects first
lap_df['LapTime'] = pd.to_timedelta(lap_df['LapTime'])

# Create a mapping from DriverNumber to FullName from race_df
# Ensure unique mapping as a driver might appear multiple times in race_df
driver_name_map = race_df[['DriverNumber', 'FullName']].drop_duplicates(subset=['DriverNumber']).set_index('DriverNumber')['FullName']

for driver_num in lap_df['DriverNumber'].unique():
    # Select laps for the current driver number and convert LapTime to total seconds
    laps_seconds = lap_df[lap_df['DriverNumber'] == driver_num]['LapTime'].dt.total_seconds().dropna()

    if len(laps_seconds) > 5:  # ensure enough data
        mean = laps_seconds.mean()
        std = laps_seconds.std()
        driver_stats[driver_num] = (mean, std)

print("Driver Lap Time Statistics (Mean, Std Dev in Seconds):")
for driver, stats in driver_stats.items():
  # get driver name from the mapping
  driver_name = driver_name_map.get(driver, "Name Not Found") # Use .get() for safer lookup
  print(f"Driver {driver} ({driver_name}): Mean = {stats[0]:.3f}s, Std Dev = {stats[1]:.3f}s")

def simulate_race(driver_stats, num_laps=60):
    race_times = {}

    for driver, (mean, std) in driver_stats.items():
      # simulate laps
      laps = np.random.normal(mean, std, num_laps)

      # Fix: Use explicit multiplication operator *
      laps = np.clip(laps, mean - 3 * std, mean + 3 * std)

      total_time = laps.sum()
      race_times[driver] = total_time

    # winner = lowest total time
    winner = min(race_times, key=race_times.get)
    return winner

#def time_to_min(time_str):
#  if pd.isna(time_str) or time_str == '' or time_str == 'None':
#       return None
#  try:
#        return pd.to_timedelta(time_str).total_seconds() / 60
#  except:
#        return None

#race_results['Q1_min'] = race_results['Q1'].apply(time_to_min)
#race_results['Q2_min'] = race_results['Q2'].apply(time_to_min)
#race_results['Q3_min'] = race_results['Q3'].apply(time_to_min)

#def get_fastest_qualifying(row):
#    times = [row['Q1_min'], row['Q2_min'], row['Q3_min']]
#    valid_times = [time_str for time_str in times if t is not None]
#    return min(valid_times) if valid_times else None

#race_results['Qualifying'] = race_results.apply(get_fastest_qualifying)
#race_results['Race'] = race_results['ElapsedTime'].apply(time_to_min)

#df_rm = race_results.dropna(subset=['Qualifying', 'Race'])

#fig = px.scatter(df_rm, x='Qualifying', y='Race', name='FullName', title='Qualifying vs Finish Time')
#fig.show()

def to_min(t):
    try:
        return pd.to_timedelta(t).total_seconds() / 60
    except:
        return None


def get_fastest_qualifying(row):
    times = []
    for col in ['Q1', 'Q2', 'Q3']:
        t = to_min(row[col])
        if t is not None:
            times.append(t)
    return min(times) if times else None

race_results['Qualifying'] = race_results.apply(get_fastest_qualifying, axis=1)
race_results['Race'] = race_results['ElapsedTime'].apply(to_min)


df_clean = race_results.dropna(subset=['Qual', 'Race'])
fig = px.scatter(df_clean, x='Qual', y='Race', hover_name='FullName')
fig.show()

print(f"Correlation: {df_clean['Qualifying'].corr(df_clean['Race']):.3f}")


unique_races = sorted(df_clean['Round'].unique())
for race in unique_races:
    df_race = df_clean[df_clean['Round'] == race]
    event_name = df_race['Event Name'].iloc[0]

    fig = px.scatter(df_race, x='Qual', y='Race', hover_name='FullName',
                     title=f'Round {int(race)}: {event_name}',
                     labels={'Qual': 'Qualifying Time (min)', 'Race': 'Race Time (min)'})
    fig.show()

import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.utils import resample
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import warnings
warnings.filterwarnings('ignore')

# Load data
race_results = pd.read_csv("https://raw.githubusercontent.com/SZRoberson/CQ2026_DataTrack/main/data/RaceResults.csv")

# Convert to minutes
def to_min(t):
    try:
        return pd.to_timedelta(t).total_seconds() / 60
    except:
        return None

# Get fastest qualifying time
def get_fastest_qualifying(row):
    times = []
    for col in ['Q1', 'Q2', 'Q3']:
        t = to_min(row[col])
        if t is not None:
            times.append(t)
    return min(times) if times else None

# Prepare features for all historical data
race_results['Qual'] = race_results.apply(get_fastest_qualifying, axis=1)
race_results['Race'] = race_results['ElapsedTime'].apply(to_min)

# Create target variables
race_results['Won'] = (race_results['Position'] == 1).astype(int)
race_results['Podium'] = (race_results['Position'] <= 3).astype(int)
race_results['Top5'] = (race_results['Position'] <= 5).astype(int)
race_results['Points'] = race_results['Points'].fillna(0)

# Create historical features for all races
def prepare_features_all(df):
    """Prepare features for all historical data"""
    features = pd.DataFrame()

    features['qualifying_time'] = df['Qual']
    features['grid_position'] = df['GridPosition']
    features['race_round'] = df['Round']

    # Fill missing values
    features = features.fillna(features.mean())

    return features

# Train models on all historical data
def train_historical_models(df_historical, n_bootstrap=500):
    """
    Train models on all historical race data
    """
    X_historical = prepare_features_all(df_historical)

    models = {}

    targets = {
        'Win (1st)': 'Won',
        'Podium (1st-3rd)': 'Podium',
        'Top 5': 'Top5'
    }

    for target_name, target_col in targets.items():
        print(f"\nTraining model for {target_name}...")
        y_historical = df_historical[target_col]

        # Check if we have both classes
        if y_historical.sum() < 3 or (len(y_historical) - y_historical.sum()) < 3:
            print(f"  Not enough data for {target_name}, using simple heuristic")
            models[target_name] = None
            continue

        # Bootstrap to get multiple models
        model_list = []
        scaler_list = []

        for i in range(n_bootstrap):
            # Resample with replacement
            indices = resample(range(len(X_historical)),
                              n_samples=len(X_historical),
                              replace=True,
                              random_state=i)
            X_boot = X_historical.iloc[indices]
            y_boot = y_historical.iloc[indices]

            # Check if we have both classes in bootstrap sample
            if len(np.unique(y_boot)) < 2:
                continue

            # Scale features
            scaler = StandardScaler()
            X_scaled = scaler.fit_transform(X_boot)

            # Train model
            model = LogisticRegression(max_iter=1000, random_state=i)
            model.fit(X_scaled, y_boot)

            model_list.append(model)
            scaler_list.append(scaler)

            if (i + 1) % 100 == 0:
                print(f"  Completed {i + 1}/{n_bootstrap} bootstraps")

        models[target_name] = {
            'models': model_list,
            'scalers': scaler_list,
            'features': X_historical.columns.tolist()
        }

        print(f"  Trained {len(model_list)} models")

    return models

# Predict for a specific race
def predict_race_outcomes(race_data, historical_models, n_bootstrap=500):
    """
    Predict outcomes for a specific Grand Prix using historical models
    """
    print(f"\n{'='*60}")
    print(f"PREDICTIONS FOR: {race_data['Event Name'].iloc[0]} (Round {int(race_data['Round'].iloc[0])})")
    print(f"{'='*60}\n")

    # Prepare features for this race
    X_race = prepare_features_all(race_data)

    all_predictions = {}

    for target_name, model_dict in historical_models.items():
        print(f"\n--- Predicting {target_name} ---")

        if model_dict is None:
            # Use simple heuristic
            print("  Using heuristic-based prediction")
            race_data_copy = race_data.copy()
            race_data_copy['prob'] = 1 / (race_data_copy['GridPosition'] + 3)
            race_data_copy['prob'] = race_data_copy['prob'] / race_data_copy['prob'].max()

            pred_df = race_data_copy[['FullName', 'DriverId', 'TeamName', 'GridPosition', 'prob']].copy()
            pred_df['probability'] = pred_df['prob']
            pred_df['prob_lower'] = pred_df['prob']
            pred_df['prob_upper'] = pred_df['prob']

            all_predictions[target_name] = pred_df.sort_values('probability', ascending=False)
            continue

        # Make predictions with all bootstrapped models
        all_probs = []

        for model, scaler in zip(model_dict['models'], model_dict['scalers']):
            X_scaled = scaler.transform(X_race)
            probas = model.predict_proba(X_scaled)[:, 1]
            all_probs.append(probas)

        if not all_probs:
            print("  No valid predictions, using heuristic")
            continue

        all_probs = np.array(all_probs)

        # Calculate statistics
        mean_probs = np.mean(all_probs, axis=0)
        lower_ci = np.percentile(all_probs, 2.5, axis=0)
        upper_ci = np.percentile(all_probs, 97.5, axis=0)

        # Create prediction dataframe
        pred_df = race_data[['FullName', 'DriverId', 'TeamName', 'GridPosition']].copy()
        pred_df['probability'] = mean_probs
        pred_df['prob_lower'] = lower_ci
        pred_df['prob_upper'] = upper_ci

        # Sort by probability
        pred_df = pred_df.sort_values('probability', ascending=False)

        all_predictions[target_name] = pred_df

        # Display top predictions
        print(f"\nTop 10 probabilities for {target_name}:")
        print(pred_df[['FullName', 'TeamName', 'GridPosition', 'probability']].head(10).to_string(index=False))
        print(f"\n{'-'*60}")

    return all_predictions

# Function to create visualizations
def create_prediction_visualizations(predictions, race_data):
    """
    Create comprehensive visualizations for predictions
    """
    if 'Win (1st)' in predictions:
        win_probs = predictions['Win (1st)'].head(15)
        fig1 = px.bar(win_probs, x='FullName', y='probability',
                      title=f'Win Probability - {race_data["Event Name"].iloc[0]}',
                      labels={'probability': 'Probability', 'FullName': 'Driver'},
                      color='probability', color_continuous_scale='Viridis',
                      text=win_probs['probability'].apply(lambda x: f'{x:.1%}'))
        fig1.update_traces(textposition='outside')
        fig1.show()

    if 'Podium (1st-3rd)' in predictions:
        podium_probs = predictions['Podium (1st-3rd)'].head(15)
        fig2 = px.bar(podium_probs, x='FullName', y='probability',
                      title=f'Podium Probability - {race_data["Event Name"].iloc[0]}',
                      labels={'probability': 'Probability', 'FullName': 'Driver'},
                      color='probability', color_continuous_scale='Plasma',
                      text=podium_probs['probability'].apply(lambda x: f'{x:.1%}'))
        fig2.update_traces(textposition='outside')
        fig2.show()

    if 'Top 5' in predictions:
        top5_probs = predictions['Top 5'].head(15)
        fig3 = px.bar(top5_probs, x='FullName', y='probability',
                      title=f'Top 5 Probability - {race_data["Event Name"].iloc[0]}',
                      labels={'probability': 'Probability', 'FullName': 'Driver'},
                      color='probability', color_continuous_scale='Inferno',
                      text=top5_probs['probability'].apply(lambda x: f'{x:.1%}'))
        fig3.update_traces(textposition='outside')
        fig3.show()

    # Combined Dashboard
    fig4 = make_subplots(
        rows=3, cols=1,
        subplot_titles=['Win Probability', 'Podium Probability', 'Top 5 Probability'],
        vertical_spacing=0.1
    )

    # Add traces for each prediction type
    for i, (key, title, row) in enumerate([
        ('Win (1st)', 'Win', 1),
        ('Podium (1st-3rd)', 'Podium', 2),
        ('Top 5', 'Top 5', 3)
    ]):
        if key in predictions:
            prob_df = predictions[key].head(10)
            fig4.add_trace(
                go.Bar(x=prob_df['FullName'], y=prob_df['probability'],
                       name=title, text=prob_df['probability'].apply(lambda x: f'{x:.1%}'),
                       textposition='outside'),
                row=row, col=1
            )

    fig4.update_layout(height=900, title_text=f"Race Outcome Predictions - {race_data['Event Name'].iloc[0]}",
                       showlegend=False)
    fig4.update_xaxes(title_text="Driver", row=3, col=1)
    fig4.update_yaxes(title_text="Probability", row=1, col=1)
    fig4.show()

# Main execution
print("Loading and preparing data...")
df_clean = race_results.dropna(subset=['Qual', 'Race']).copy()
print(f"Total drivers with complete data: {len(df_clean)}")
print(f"Races included: {sorted(df_clean['Round'].unique())}\n")

# Train models on all historical data (excluding the target race)
target_race = df_clean['Round'].max()
historical_data = df_clean[df_clean['Round'] < target_race].copy()

print(f"Training models on {len(historical_data['Round'].unique())} historical races...")
historical_models = train_historical_models(historical_data, n_bootstrap=200)

# Predict for the most recent race
race_to_predict = df_clean[df_clean['Round'] == target_race].copy()
predictions = predict_race_outcomes(race_to_predict, historical_models, n_bootstrap=200)

# Create visualizations
create_prediction_visualizations(predictions, race_to_predict)

# Print summary
print(f"\n{'='*60}")
print(f"PREDICTION SUMMARY - {race_to_predict['Event Name'].iloc[0]}")
print(f"{'='*60}")

if 'Win (1st)' in predictions:
    print("\nTop 5 Win Probabilities:")
    for idx, row in predictions['Win (1st)'].head(5).iterrows():
        print(f"  {row['FullName']:20} ({row['TeamName']}): {row['probability']:.1%}")

if 'Podium (1st-3rd)' in predictions:
    print("\nTop 5 Podium Probabilities:")
    for idx, row in predictions['Podium (1st-3rd)'].head(5).iterrows():
        print(f"  {row['FullName']:20} ({row['TeamName']}): {row['probability']:.1%}")

if 'Top 5' in predictions:
    print("\nTop 5 to be in the Top 5 Probabilities:")
    for idx, row in predictions['Top 5'].head(5).iterrows():
        print(f"  {row['FullName']:20} ({row['TeamName']}): {row['probability']:.1%}")

import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from collections import defaultdict

# ----------------------------
# LOAD DATA
# ----------------------------
lap_data = pd.read_csv("LapTimes.csv")
results_data = pd.read_csv("RaceResults.csv")

# ----------------------------
# FEATURE ENGINEERING
# ----------------------------

# Aggregate lap stats per driver per race
lap_features = lap_data.groupby(['raceId', 'driverId']).agg(
    mean_lap=('lapTime', 'mean'),
    std_lap=('lapTime', 'std'),
    best_lap=('lapTime', 'min')
).reset_index()

# Merge with race results
data = results_data.merge(lap_features, on=['raceId', 'driverId'])

# Create target variable
data['win'] = (data['position'] == 1).astype(int)

# Drop missing values
data = data.dropna()

# ----------------------------
# BOOTSTRAPPED LOGISTIC MODEL
# ----------------------------

def bootstrap_logistic(track_data, n_bootstrap=500):
    drivers = track_data['driverId'].unique()
    prob_distributions = {d: [] for d in drivers}

    features = ['mean_lap', 'std_lap', 'best_lap', 'grid']

    for _ in range(n_bootstrap):
        # Resample with replacement
        sample = track_data.sample(frac=1, replace=True)

        X = sample[features]
        y = sample['win']

        # Train model
        model = LogisticRegression(max_iter=1000)
        model.fit(X, y)

        # Predict probabilities for all drivers in this track
        X_all = track_data[features]
        probs = model.predict_proba(X_all)[:, 1]

        for driver, prob in zip(track_data['driverId'], probs):
            prob_distributions[driver].append(prob)

    return prob_distributions

# ----------------------------
# RUN PER TRACK
# ----------------------------

track_probabilities = {}

for track in data['circuitId'].unique():
    track_data = data[data['circuitId'] == track]

    # Require enough samples
    if len(track_data) < 50:
        continue

    prob_dist = bootstrap_logistic(track_data)

    # Aggregate results
    summary = {}
    for driver, probs in prob_dist.items():
        summary[driver] = {
            'mean_prob': np.mean(probs),
            'std_prob': np.std(probs)
        }

    track_probabilities[track] = summary

# ----------------------------
# DISPLAY RESULTS
# ----------------------------

for track, drivers in track_probabilities.items():
    print(f"\nTrack {track}")
    sorted_drivers = sorted(drivers.items(), key=lambda x: x[1]['mean_prob'], reverse=True)

    for driver, stats in sorted_drivers:
        print(f"Driver {driver}: {stats['mean_prob']:.3f} ± {stats['std_prob']:.3f}")

import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.utils import resample
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import warnings
warnings.filterwarnings('ignore')

# Load data
race_results = pd.read_csv("https://raw.githubusercontent.com/SZRoberson/CQ2026_DataTrack/main/data/RaceResults.csv")

# Convert to minutes
def to_min(t):
    try:
        return pd.to_timedelta(t).total_seconds() / 60
    except:
        return None

# Get fastest qualifying time
def get_fastest_qualifying(row):
    times = []
    for col in ['Q1', 'Q2', 'Q3']:
        t = to_min(row[col])
        if t is not None:
            times.append(t)
    return min(times) if times else None

# Prepare features for all historical data
race_results['Qual'] = race_results.apply(get_fastest_qualifying, axis=1)
race_results['Race'] = race_results['ElapsedTime'].apply(to_min)

# Create target variables
race_results['Won'] = (race_results['Position'] == 1).astype(int)
race_results['Podium'] = (race_results['Position'] <= 3).astype(int)
race_results['Top5'] = (race_results['Position'] <= 5).astype(int)
race_results['Points'] = race_results['Points'].fillna(0)

# Create historical features for all races
def prepare_features_all(df):
    """Prepare features for all historical data"""
    features = pd.DataFrame()

    features['qualifying_time'] = df['Qual']
    features['grid_position'] = df['GridPosition']
    features['race_round'] = df['Round']

    # Fill missing values
    features = features.fillna(features.mean())

    return features

# Train models on all historical data
def train_historical_models(df_historical, n_bootstrap=500):
    """
    Train models on all historical race data
    """
    X_historical = prepare_features_all(df_historical)

    models = {}

    targets = {
        'Win (1st)': 'Won',
        'Podium (1st-3rd)': 'Podium',
        'Top 5': 'Top5'
    }

    for target_name, target_col in targets.items():
        print(f"\nTraining model for {target_name}...")
        y_historical = df_historical[target_col]

        # Check if we have both classes
        if y_historical.sum() < 3 or (len(y_historical) - y_historical.sum()) < 3:
            print(f"  Not enough data for {target_name}, using simple heuristic")
            models[target_name] = None
            continue

        # Bootstrap to get multiple models
        model_list = []
        scaler_list = []

        for i in range(n_bootstrap):
            # Resample with replacement
            indices = resample(range(len(X_historical)),
                              n_samples=len(X_historical),
                              replace=True,
                              random_state=i)
            X_boot = X_historical.iloc[indices]
            y_boot = y_historical.iloc[indices]

            # Check if we have both classes in bootstrap sample
            if len(np.unique(y_boot)) < 2:
                continue

            # Scale features
            scaler = StandardScaler()
            X_scaled = scaler.fit_transform(X_boot)

            # Train model
            model = LogisticRegression(max_iter=1000, random_state=i)
            model.fit(X_scaled, y_boot)

            model_list.append(model)
            scaler_list.append(scaler)

            if (i + 1) % 100 == 0:
                print(f"  Completed {i + 1}/{n_bootstrap} bootstraps")

        models[target_name] = {
            'models': model_list,
            'scalers': scaler_list,
            'features': X_historical.columns.tolist()
        }

        print(f"  Trained {len(model_list)} models")

    return models

# Predict for a specific race
def predict_race_outcomes(race_data, historical_models):
    """
    Predict outcomes for a specific Grand Prix using historical models
    """
    print(f"\n{'='*60}")
    print(f"PREDICTIONS FOR: {race_data['Event Name'].iloc[0]} (Round {int(race_data['Round'].iloc[0])})")
    print(f"{'='*60}\n")

    # Prepare features for this race
    X_race = prepare_features_all(race_data)

    all_predictions = {}

    for target_name, model_dict in historical_models.items():
        print(f"\n--- Predicting {target_name} ---")

        if model_dict is None:
            # Use simple heuristic
            print("  Using heuristic-based prediction")
            race_data_copy = race_data.copy()
            race_data_copy['prob'] = 1 / (race_data_copy['GridPosition'] + 3)
            race_data_copy['prob'] = race_data_copy['prob'] / race_data_copy['prob'].max()

            pred_df = race_data_copy[['FullName', 'DriverId', 'TeamName', 'GridPosition', 'prob']].copy()
            pred_df['probability'] = pred_df['prob']
            pred_df['prob_lower'] = pred_df['prob']
            pred_df['prob_upper'] = pred_df['prob']

            all_predictions[target_name] = pred_df.sort_values('probability', ascending=False)
            continue

        # Make predictions with all bootstrapped models
        all_probs = []

        for model, scaler in zip(model_dict['models'], model_dict['scalers']):
            X_scaled = scaler.transform(X_race)
            probas = model.predict_proba(X_scaled)[:, 1]
            all_probs.append(probas)

        if not all_probs:
            print("  No valid predictions, using heuristic")
            continue

        all_probs = np.array(all_probs)

        # Calculate statistics
        mean_probs = np.mean(all_probs, axis=0)
        lower_ci = np.percentile(all_probs, 2.5, axis=0)
        upper_ci = np.percentile(all_probs, 97.5, axis=0)

        # Create prediction dataframe
        pred_df = race_data[['FullName', 'DriverId', 'TeamName', 'GridPosition']].copy()
        pred_df['probability'] = mean_probs
        pred_df['prob_lower'] = lower_ci
        pred_df['prob_upper'] = upper_ci

        # Sort by probability
        pred_df = pred_df.sort_values('probability', ascending=False)

        all_predictions[target_name] = pred_df

        # Display top predictions
        print(f"\nTop 10 probabilities for {target_name}:")
        print(pred_df[['FullName', 'TeamName', 'GridPosition', 'probability']].head(10).to_string(index=False))
        print(f"\n{'-'*60}")

    return all_predictions

# Function to filter predictions
def filter_predictions(predictions, filter_type, filter_value):
    """
    Filter predictions by driver, team, or track
    """
    filtered = {}

    for target_name, pred_df in predictions.items():
        if filter_type == "Driver":
            filtered_df = pred_df[pred_df['FullName'] == filter_value].copy()
        elif filter_type == "Team":
            filtered_df = pred_df[pred_df['TeamName'] == filter_value].copy()
        elif filter_type == "Track":
            # For track filtering, we need to filter the race data
            # This is handled by selecting a different race
            filtered_df = pred_df.copy()
        else:
            filtered_df = pred_df.copy()

        filtered[target_name] = filtered_df

    return filtered

# Function to create all visualizations and return as list
def create_figure_list(predictions, race_data, filter_type="All", filter_value=None):
    """
    Create all figures and return them in a list
    """
    figure_list = []

    # Filter predictions if needed
    if filter_type != "All" and filter_value:
        predictions = filter_predictions(predictions, filter_type, filter_value)

    # Figure 1: Win Probability Bar Chart
    if 'Win (1st)' in predictions and len(predictions['Win (1st)']) > 0:
        win_probs = predictions['Win (1st)'].head(15)

        title_text = f'Win Probability'
        if filter_type == "Driver" and filter_value:
            title_text = f'Win Probability - {filter_value}'
        elif filter_type == "Team" and filter_value:
            title_text = f'Win Probability - {filter_value}'
        else:
            title_text = f'Win Probability - {race_data["Event Name"].iloc[0]}'

        fig1 = px.bar(win_probs, x='FullName', y='probability',
                      title=title_text,
                      labels={'probability': 'Probability', 'FullName': 'Driver'},
                      color='probability',
                      color_continuous_scale='Viridis',
                      text=win_probs['probability'].apply(lambda x: f'{x:.1%}'))
        fig1.update_layout(height=500, showlegend=False)
        fig1.update_traces(textposition='outside')
        figure_list.append(fig1)

    # Figure 2: Podium Probability Bar Chart
    if 'Podium (1st-3rd)' in predictions and len(predictions['Podium (1st-3rd)']) > 0:
        podium_probs = predictions['Podium (1st-3rd)'].head(15)

        title_text = f'Podium Probability'
        if filter_type == "Driver" and filter_value:
            title_text = f'Podium Probability - {filter_value}'
        elif filter_type == "Team" and filter_value:
            title_text = f'Podium Probability - {filter_value}'
        else:
            title_text = f'Podium Probability - {race_data["Event Name"].iloc[0]}'

        fig2 = px.bar(podium_probs, x='FullName', y='probability',
                      title=title_text,
                      labels={'probability': 'Probability', 'FullName': 'Driver'},
                      color='probability',
                      color_continuous_scale='Plasma',
                      text=podium_probs['probability'].apply(lambda x: f'{x:.1%}'))
        fig2.update_layout(height=500, showlegend=False)
        fig2.update_traces(textposition='outside')
        figure_list.append(fig2)

    # Figure 3: Top 5 Probability Bar Chart
    if 'Top 5' in predictions and len(predictions['Top 5']) > 0:
        top5_probs = predictions['Top 5'].head(15)

        title_text = f'Top 5 Probability'
        if filter_type == "Driver" and filter_value:
            title_text = f'Top 5 Probability - {filter_value}'
        elif filter_type == "Team" and filter_value:
            title_text = f'Top 5 Probability - {filter_value}'
        else:
            title_text = f'Top 5 Probability - {race_data["Event Name"].iloc[0]}'

        fig3 = px.bar(top5_probs, x='FullName', y='probability',
                      title=title_text,
                      labels={'probability': 'Probability', 'FullName': 'Driver'},
                      color='probability',
                      color_continuous_scale='Inferno',
                      text=top5_probs['probability'].apply(lambda x: f'{x:.1%}'))
        fig3.update_layout(height=500, showlegend=False)
        fig3.update_traces(textposition='outside')
        figure_list.append(fig3)

    # Figure 4: Confidence Intervals (only for full race view)
    if filter_type == "All" and 'Win (1st)' in predictions:
        top_drivers = predictions['Win (1st)'].head(8).copy()

        fig4 = go.Figure()
        fig4.add_trace(go.Bar(
            x=top_drivers['FullName'],
            y=top_drivers['probability'],
            name='Probability',
            marker_color='steelblue',
            text=top_drivers['probability'].apply(lambda x: f'{x:.1%}'),
            textposition='outside',
            error_y=dict(
                type='data',
                symmetric=False,
                array=top_drivers['prob_upper'] - top_drivers['probability'],
                arrayminus=top_drivers['probability'] - top_drivers['prob_lower'],
                color='gray',
                thickness=1
            )
        ))

        fig4.update_layout(
            title=f'Win Probabilities with 95% Confidence Intervals - {race_data["Event Name"].iloc[0]}',
            xaxis_title='',
            yaxis_title='Probability',
            height=500,
            showlegend=False
        )
        figure_list.append(fig4)

    # Figure 5: Driver-specific chart (if a driver is selected)
    if filter_type == "Driver" and filter_value and 'Win (1st)' in predictions:
        driver_data = predictions['Win (1st)']
        if len(driver_data) > 0:
            driver_row = driver_data.iloc[0]

            categories = ['Win', 'Podium', 'Top 5']
            values = [
                driver_row['probability'] * 100,
                predictions['Podium (1st-3rd)'].iloc[0]['probability'] * 100 if 'Podium (1st-3rd)' in predictions else 0,
                predictions['Top 5'].iloc[0]['probability'] * 100 if 'Top 5' in predictions else 0
            ]

            fig5 = go.Figure()
            fig5.add_trace(go.Bar(
                x=categories,
                y=values,
                marker_color=['#FFD700', '#C0C0C0', '#CD7F32'],
                text=[f'{v:.1f}%' for v in values],
                textposition='auto'
            ))

            fig5.update_layout(
                title=f'{filter_value} - Outcome Probabilities',
                yaxis_title='Probability (%)',
                yaxis_range=[0, 100],
                height=400
            )
            figure_list.append(fig5)

    # Figure 6: Team comparison (if a team is selected)
    if filter_type == "Team" and filter_value and 'Win (1st)' in predictions:
        team_data = predictions['Win (1st)']
        if len(team_data) > 0:
            team_drivers = team_data[['FullName', 'probability']].copy()
            if 'Podium (1st-3rd)' in predictions:
                team_drivers['podium'] = predictions['Podium (1st-3rd)']['probability']
            if 'Top 5' in predictions:
                team_drivers['top5'] = predictions['Top 5']['probability']

            fig6 = go.Figure()

            fig6.add_trace(go.Bar(
                name='Win',
                x=team_drivers['FullName'],
                y=team_drivers['probability'] * 100,
                marker_color='#FFD700'
            ))

            if 'podium' in team_drivers.columns:
                fig6.add_trace(go.Bar(
                    name='Podium',
                    x=team_drivers['FullName'],
                    y=team_drivers['podium'] * 100,
                    marker_color='#C0C0C0'
                ))

            if 'top5' in team_drivers.columns:
                fig6.add_trace(go.Bar(
                    name='Top 5',
                    x=team_drivers['FullName'],
                    y=team_drivers['top5'] * 100,
                    marker_color='#CD7F32'
                ))

            fig6.update_layout(
                title=f'{filter_value} - Driver Comparison',
                yaxis_title='Probability (%)',
                barmode='group',
                height=500
            )
            figure_list.append(fig6)

    return figure_list

# Main execution with interactive filtering
print("Loading and preparing data...")
df_clean = race_results.dropna(subset=['Qual', 'Race']).copy()
print(f"Total drivers with complete data: {len(df_clean)}")
print(f"Races included: {sorted(df_clean['Round'].unique())}\n")

# Train models on all historical data (excluding the target race)
target_race = df_clean['Round'].max()
historical_data = df_clean[df_clean['Round'] < target_race].copy()

print(f"Training models on {len(historical_data['Round'].unique())} historical races...")
historical_models = train_historical_models(historical_data, n_bootstrap=200)

# Get all available races for selection
available_races = sorted(df_clean['Round'].unique())
race_options = {}
for r in available_races:
    race_info = df_clean[df_clean['Round'] == r].iloc[0]
    race_options[r] = f"Round {int(r)}: {race_info['Event Name']} ({race_info['Location']}, {race_info['Country']})"

# Get all drivers and teams for filtering
all_drivers = sorted(df_clean['FullName'].unique())
all_teams = sorted(df_clean['TeamName'].unique())

# Interactive selection menu
print("\n" + "="*60)
print("INTERACTIVE PREDICTION TOOL")
print("="*60)

# Select race
print("\nAvailable Grands Prix:")
for i, (round_num, label) in enumerate(race_options.items(), 1):
    print(f"  {i}. {label}")
print(f"  {len(race_options)+1}. Custom race number")

race_choice = input(f"\nSelect a race (1-{len(race_options)+1}): ")

try:
    race_choice = int(race_choice)
    if 1 <= race_choice <= len(race_options):
        selected_race = list(race_options.keys())[race_choice - 1]
    else:
        selected_race = int(input("Enter race round number: "))
except:
    selected_race = target_race

# Select filter type
print("\nFilter options:")
print("  1. No filter (show all drivers)")
print("  2. Filter by Driver")
print("  3. Filter by Team")

filter_choice = input("\nSelect filter option (1-3): ")

filter_type = "All"
filter_value = None

if filter_choice == "2":
    print("\nAvailable drivers:")
    for i, driver in enumerate(all_drivers, 1):
        print(f"  {i}. {driver}")
    driver_choice = int(input(f"\nSelect driver (1-{len(all_drivers)}): "))
    filter_type = "Driver"
    filter_value = all_drivers[driver_choice - 1]

elif filter_choice == "3":
    print("\nAvailable teams:")
    for i, team in enumerate(all_teams, 1):
        print(f"  {i}. {team}")
    team_choice = int(input(f"\nSelect team (1-{len(all_teams)}): "))
    filter_type = "Team"
    filter_value = all_teams[team_choice - 1]

# Get the race data
race_to_predict = df_clean[df_clean['Round'] == selected_race].copy()

if len(race_to_predict) == 0:
    print(f"\nError: No data found for Round {selected_race}")
else:
    # Make predictions
    predictions = predict_race_outcomes(race_to_predict, historical_models)

    # Create figure list
    figure_list = create_figure_list(predictions, race_to_predict, filter_type, filter_value)

    # Display all figures
    print(f"\n{'='*60}")
    print(f"DISPLAYING {len(figure_list)} FIGURES")
    print(f"{'='*60}\n")

    for i, fig in enumerate(figure_list, 1):
        print(f"\n--- Figure {i} ---")
        fig.show()

    # Display summary table
    print(f"\n{'='*60}")
    print(f"PREDICTION SUMMARY - {race_to_predict['Event Name'].iloc[0]}")
    print(f"{'='*60}")

    if filter_type == "All":
        if 'Win (1st)' in predictions:
            print("\nTop 10 Win Probabilities:")
            for idx, row in predictions['Win (1st)'].head(10).iterrows():
                print(f"  {row['FullName']:25} ({row['TeamName']}): {row['probability']:.1%} "
                      f"(95% CI: {row['prob_lower']:.1%}-{row['prob_upper']:.1%})")

    elif filter_type == "Driver" and filter_value:
        if 'Win (1st)' in predictions and len(predictions['Win (1st)']) > 0:
            driver_row = predictions['Win (1st)'].iloc[0]
            print(f"\nDriver: {filter_value}")
            print(f"  Win Probability: {driver_row['probability']:.1%} "
                  f"(95% CI: {driver_row['prob_lower']:.1%}-{driver_row['prob_upper']:.1%})")

            if 'Podium (1st-3rd)' in predictions and len(predictions['Podium (1st-3rd)']) > 0:
                podium_row = predictions['Podium (1st-3rd)'].iloc[0]
                print(f"  Podium Probability: {podium_row['probability']:.1%}")

            if 'Top 5' in predictions and len(predictions['Top 5']) > 0:
                top5_row = predictions['Top 5'].iloc[0]
                print(f"  Top 5 Probability: {top5_row['probability']:.1%}")

    elif filter_type == "Team" and filter_value:
        print(f"\nTeam: {filter_value}")
        team_predictions = predictions['Win (1st)'][predictions['Win (1st)']['TeamName'] == filter_value]
        for idx, row in team_predictions.iterrows():
            print(f"  {row['FullName']:20}: {row['probability']:.1%} win probability")